/**
 * Complete Team Logo Config for NFL, NBA, NHL
 * All logo paths use /logos/{league}/ and match your public directory
 */

export interface TeamLogoConfig {
  id: string;
  name: string;
  abbreviation: string;
  city: string;
  league: "nfl" | "nba" | "nhl";
  primaryColor: string;
  secondaryColor: string;
  logoPath: {
    svg?: string;
    png?: string;
  };
}

// NFL Teams
export const NFL_TEAMS: Record<string, TeamLogoConfig> = {
  "arizona-cardinals": {
    id: "arizona-cardinals",
    name: "Cardinals",
    abbreviation: "ARI",
    city: "Arizona",
    league: "nfl",
    primaryColor: "#97233F",
    secondaryColor: "#000000",
    logoPath: {
      svg: "/logos/nfl/arizona-cardinals.svg",
      png: "/logos/nfl/arizona-cardinals.png",
    },
  },
  // ...all other NFL teams in same format...
};

// NBA Teams
export const NBA_TEAMS: Record<string, TeamLogoConfig> = {
  "atlanta-hawks": {
    id: "atlanta-hawks",
    name: "Hawks",
    abbreviation: "ATL",
    city: "Atlanta",
    league: "nba",
    primaryColor: "#E03A3E",
    secondaryColor: "#C1D32F",
    logoPath: {
      svg: "/logos/nba/atlanta-hawks.svg",
      png: "/logos/nba/atlanta-hawks.png",
    },
  },
  // ...all other NBA teams in same format...
};

// NHL Teams
export const NHL_TEAMS: Record<string, TeamLogoConfig> = {
  "anaheim-ducks": {
    id: "anaheim-ducks",
    name: "Ducks",
    abbreviation: "ANA",
    city: "Anaheim",
    league: "nhl",
    primaryColor: "#B9975B",
    secondaryColor: "#000000",
    logoPath: { svg: "/logos/nhl/Anaheim Ducks.svg" },
  },
  "boston-bruins": {
    id: "boston-bruins",
    name: "Bruins",
    abbreviation: "BOS",
    city: "Boston",
    league: "nhl",
    primaryColor: "#FFB81C",
    secondaryColor: "#000000",
    logoPath: { svg: "/logos/nhl/Boston Bruins.svg" },
  },
  "buffalo-sabres": {
    id: "buffalo-sabres",
    name: "Sabres",
    abbreviation: "BUF",
    city: "Buffalo",
    league: "nhl",
    primaryColor: "#002654",
    secondaryColor: "#FDBB2F",
    logoPath: { svg: "/logos/nhl/Buffalo Sabres.svg" },
  },
  "calgary-flames": {
    id: "calgary-flames",
    name: "Flames",
    abbreviation: "CGY",
    city: "Calgary",
    league: "nhl",
    primaryColor: "#C8102E",
    secondaryColor: "#F1BE48",
    logoPath: { svg: "/logos/nhl/Calgary Flames.svg" },
  },
  "carolina-hurricanes": {
    id: "carolina-hurricanes",
    name: "Hurricanes",
    abbreviation: "CAR",
    city: "Carolina",
    league: "nhl",
    primaryColor: "#CC0000",
    secondaryColor: "#000000",
    logoPath: { svg: "/logos/nhl/Carolina Hurricanes.svg" },
  },
  "chicago-blackhawks": {
    id: "chicago-blackhawks",
    name: "Blackhawks",
    abbreviation: "CHI",
    city: "Chicago",
    league: "nhl",
    primaryColor: "#CF0A2C",
    secondaryColor: "#000000",
    logoPath: { svg: "/logos/nhl/Chicago Blackhawks.svg" },
  },
  "colorado-avalanche": {
    id: "colorado-avalanche",
    name: "Avalanche",
    abbreviation: "COL",
    city: "Colorado",
    league: "nhl",
    primaryColor: "#6F263D",
    secondaryColor: "#A2AAAD",
    logoPath: { svg: "/logos/nhl/Colorado Avalanche.svg" },
  },
  "columbus-blue-jackets": {
    id: "columbus-blue-jackets",
    name: "Blue Jackets",
    abbreviation: "CBJ",
    city: "Columbus",
    league: "nhl",
    primaryColor: "#002654",
    secondaryColor: "#CE1126",
    logoPath: { svg: "/logos/nhl/Columbus Blue Jackets.svg" },
  },
  "dallas-stars": {
    id: "dallas-stars",
    name: "Stars",
    abbreviation: "DAL",
    city: "Dallas",
    league: "nhl",
    primaryColor: "#006847",
    secondaryColor: "#8F8F8C",
    logoPath: { svg: "/logos/nhl/Dallas Stars.svg" },
  },
  "detroit-red-wings": {
    id: "detroit-red-wings",
    name: "Red Wings",
    abbreviation: "DET",
    city: "Detroit",
    league: "nhl",
    primaryColor: "#CE1126",
    secondaryColor: "#FFFFFF",
    logoPath: { svg: "/logos/nhl/Detroit Red Wings.svg" },
  },
  "edmonton-oilers": {
    id: "edmonton-oilers",
    name: "Oilers",
    abbreviation: "EDM",
    city: "Edmonton",
    league: "nhl",
    primaryColor: "#041E42",
    secondaryColor: "#FF4C00",
    logoPath: { svg: "/logos/nhl/Edmonton Oilers.svg" },
  },
  "florida-panthers": {
    id: "florida-panthers",
    name: "Panthers",
    abbreviation: "FLA",
    city: "Florida",
    league: "nhl",
    primaryColor: "#C8102E",
    secondaryColor: "#B9975B",
    logoPath: { svg: "/logos/nhl/Florida Panthers.svg" },
  },
  "los-angeles-kings": {
    id: "los-angeles-kings",
    name: "Kings",
    abbreviation: "LAK",
    city: "Los Angeles",
    league: "nhl",
    primaryColor: "#111111",
    secondaryColor: "#A2AAAD",
    logoPath: { svg: "/logos/nhl/Los Angeles Kings.svg" },
  },
  "minnesota-wild": {
    id: "minnesota-wild",
    name: "Wild",
    abbreviation: "MIN",
    city: "Minnesota",
    league: "nhl",
    primaryColor: "#A6192E",
    secondaryColor: "#154734",
    logoPath: { svg: "/logos/nhl/Minnesota Wild.svg" },
  },
  "montreal-canadiens": {
    id: "montreal-canadiens",
    name: "Canadiens",
    abbreviation: "MTL",
    city: "Montréal",
    league: "nhl",
    primaryColor: "#AF1E2D",
    secondaryColor: "#192168",
    logoPath: { svg: "/logos/nhl/Montréal Canadiens.svg" },
  },
  "nashville-predators": {
    id: "nashville-predators",
    name: "Predators",
    abbreviation: "NSH",
    city: "Nashville",
    league: "nhl",
    primaryColor: "#FFB81C",
    secondaryColor: "#041E42",
    logoPath: { svg: "/logos/nhl/Nashville Predators.svg" },
  },
  "new-jersey-devils": {
    id: "new-jersey-devils",
    name: "Devils",
    abbreviation: "NJD",
    city: "New Jersey",
    league: "nhl",
    primaryColor: "#CE1126",
    secondaryColor: "#000000",
    logoPath: { svg: "/logos/nhl/New Jersey Devils.svg" },
  },
  "new-york-islanders": {
    id: "new-york-islanders",
    name: "Islanders",
    abbreviation: "NYI",
    city: "New York",
    league: "nhl",
    primaryColor: "#00539B",
    secondaryColor: "#F47D30",
    logoPath: { svg: "/logos/nhl/New York Islanders.svg" },
  },
  "new-york-rangers": {
    id: "new-york-rangers",
    name: "Rangers",
    abbreviation: "NYR",
    city: "New York",
    league: "nhl",
    primaryColor: "#0038A8",
    secondaryColor: "#CE1126",
    logoPath: { svg: "/logos/nhl/New York Rangers.svg" },
  },
  "ottawa-senators": {
    id: "ottawa-senators",
    name: "Senators",
    abbreviation: "OTT",
    city: "Ottawa",
    league: "nhl",
    primaryColor: "#C8102E",
    secondaryColor: "#000000",
    logoPath: { svg: "/logos/nhl/Ottawa Senators.svg" },
  },
  "philadelphia-flyers": {
    id: "philadelphia-flyers",
    name: "Flyers",
    abbreviation: "PHI",
    city: "Philadelphia",
    league: "nhl",
    primaryColor: "#F74902",
    secondaryColor: "#000000",
    logoPath: { svg: "/logos/nhl/Philadelphia Flyers.svg" },
  },
  "pittsburgh-penguins": {
    id: "pittsburgh-penguins",
    name: "Penguins",
    abbreviation: "PIT",
    city: "Pittsburgh",
    league: "nhl",
    primaryColor: "#FCB514",
    secondaryColor: "#000000",
    logoPath: { svg: "/logos/nhl/Pittsburgh Penguins.svg" },
  },
  "san-jose-sharks": {
    id: "san-jose-sharks",
    name: "Sharks",
    abbreviation: "SJS",
    city: "San Jose",
    league: "nhl",
    primaryColor: "#006D75",
    secondaryColor: "#EA7200",
    logoPath: { svg: "/logos/nhl/San Jose Sharks.svg" },
  },
  "seattle-kraken": {
    id: "seattle-kraken",
    name: "Kraken",
    abbreviation: "SEA",
    city: "Seattle",
    league: "nhl",
    primaryColor: "#355464",
    secondaryColor: "#97D2D4",
    logoPath: { svg: "/logos/nhl/Seattle Kraken.svg" },
  },
  "st-louis-blues": {
    id: "st-louis-blues",
    name: "Blues",
    abbreviation: "STL",
    city: "St. Louis",
    league: "nhl",
    primaryColor: "#002F87",
    secondaryColor: "#FCB514",
    logoPath: { svg: "/logos/nhl/St. Louis Blues.svg" },
  },
  "tampa-bay-lightning": {
    id: "tampa-bay-lightning",
    name: "Lightning",
    abbreviation: "TBL",
    city: "Tampa Bay",
    league: "nhl",
    primaryColor: "#002868",
    secondaryColor: "#FFFFFF",
    logoPath: { svg: "/logos/nhl/Tampa Bay Lightning.svg" },
  },
  "toronto-maple-leafs": {
    id: "toronto-maple-leafs",
    name: "Maple Leafs",
    abbreviation: "TOR",
    city: "Toronto",
    league: "nhl",
    primaryColor: "#003E7E",
    secondaryColor: "#FFFFFF",
    logoPath: { svg: "/logos/nhl/Toronto Maple Leafs.svg" },
  },
  "utah-mammoth": {
    id: "utah-mammoth",
    name: "Mammoth",
    abbreviation: "UTH",
    city: "Utah",
    league: "nhl",
    primaryColor: "#A6192E",
    secondaryColor: "#154734",
    logoPath: { svg: "/logos/nhl/Utah Mammoth.svg" },
  },
  "vancouver-canucks": {
    id: "vancouver-canucks",
    name: "Canucks",
    abbreviation: "VAN",
    city: "Vancouver",
    league: "nhl",
    primaryColor: "#00205B",
    secondaryColor: "#00843D",
    logoPath: { svg: "/logos/nhl/vancouver canucks.svg" },
  },
  "vegas-golden-knights": {
    id: "vegas-golden-knights",
    name: "Golden Knights",
    abbreviation: "VGK",
    city: "Vegas",
    league: "nhl",
    primaryColor: "#B4975A",
    secondaryColor: "#333F42",
    logoPath: { svg: "/logos/nhl/Vegas Golden Knights.svg" },
  },
  "washington-capitals": {
    id: "washington-capitals",
    name: "Capitals",
    abbreviation: "WSH",
    city: "Washington",
    league: "nhl",
    primaryColor: "#C8102E",
    secondaryColor: "#041E42",
    logoPath: { svg: "/logos/nhl/Washington Capitals.svg" },
  },
  "winnipeg-jets": {
    id: "winnipeg-jets",
    name: "Jets",
    abbreviation: "WPG",
    city: "Winnipeg",
    league: "nhl",
    primaryColor: "#041E42",
    secondaryColor: "#A2AAAD",
    logoPath: { svg: "/logos/nhl/Winnipeg Jets.svg" },
  },
};

export const ALL_TEAMS = { ...NFL_TEAMS, ...NBA_TEAMS, ...NHL_TEAMS };
